services:
  vpn_bittorrent:
    extends:
      file: ../vpn/container-compose.yml
      service: openvpn-client
    container_name: vpn_bittorrent
    volumes:
      - /mnt/data/container_data/vpn:/data/vpn
    ports:
      - ${BT_PORT}:${BT_PORT}
      - ${BT_PORT}:${BT_PORT}/udp
      - 8081:8081/tcp
    environment:
      - KILL_SWITCH=on
      - SUBNETS=172.18.0.0/16
      - VPN_CONFIG_FILE=
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$MY_DOMAIN`)"

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn_bittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8081
    volumes:
      - /mnt/data/container_data/qbittorrent:/config
      - /mnt/data/shared/incoming:/mnt/shared/incoming
      - /mnt/data/shared/movies:/mnt/shared/movies
      - /mnt/data/shared/tv:/mnt/shared/tv
    restart: unless-stopped

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
