services:
  vpn_general:
    extends:
      file: ../vpn/compose.yml
      service: openvpn-client
    container_name: vpn_general
    volumes:
      - /mnt/container_data/vpn:/data/vpn
    ports:
      - 8337:8337
      - 8558:8558
      - 18080:18080/tcp
      - 18089:18089/tcp
      - 9050:9050
      - 127.0.0.1:9283:80
    environment:
      - KILL_SWITCH=nftables
      - VPN_CONFIG_FILE=${VPN}
      - SUBNETS=${NETWORK}.0/24
    restart: unless-stopped

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
