datasources:
  data:
    url: /data/container_data.json

context:
  container_data:
    url: /data/container_data.json

inputFiles:
  - /input/compose/flexo/flexo.env.tmpl
  - /input/compose/powerwall/data/pypowerwall.env.tmpl
  - /input/compose/powerwall/data/telegraf.conf.tmpl
  - /input/compose/powerwall/data/weather411.conf.tmpl
  - /input/compose/smb/config.yml.tmpl
  - /input/compose/smb/.env.tmpl
  - /input/compose/syncthing/compose.yml.tmpl
  - /input/compose/syncthing/.env.tmpl
  - /input/compose/traefik/data/traefik.env.tmpl
  - /input/compose/traefik/data/traefik.yml.tmpl
  - /input/compose/vaultwarden/.env.tmpl
  - /input/compose/wg1_qbt/.env.tmpl
  - /input/compose/wg2_usenet/.env.tmpl
  - /input/compose/wg3_general/.env.tmpl
  - /input/quadlets/crowdin/.env.tmpl
  - /input/old/busybox/.env.tmpl
  - /input/old/mumble-server/mumble.env.tmpl
  - /input/old/wg_test/.env.tmpl

outputFiles:
  - /output/compose/flexo/flexo.env
  - /output/compose/powerwall/data/pypowerwall.env
  - /output/compose/powerwall/data/telegraf.conf
  - /output/compose/powerwall/data/weather411.conf
  - /output/compose/smb/config.yml
  - /output/compose/smb/.env
  - /output/compose/syncthing/compose.yml
  - /output/compose/syncthing/.env
  - /output/compose/traefik/data/traefik.env
  - /output/compose/traefik/data/traefik.yml
  - /output/compose/vaultwarden/.env
  - /output/compose/wg1_qbt/.env
  - /output/compose/wg2_usenet/.env
  - /output/compose/wg3_general/.env
  - /output/quadlets/crowdin/.env
  - /output/old/busybox/.env
  - /output/old/mumble-server/mumble.env
  - /output/old/wg_test/.env
