datasources:
  data:
    url: /data/container_data.json

context:
  container_data:
    url: /data/container_data.json

inputFiles:
  - /input/compose/vpn_general/.env.tmpl
  - /input/compose/beets/.env.tmpl
  - /input/compose/bitwarden/.env.tmpl
  - /input/compose/busybox/.env.tmpl
  - /input/compose/flexo/compose.yml.tmpl
  - /input/compose/flexo/.env.tmpl
  - /input/compose/imapfilter/.env.tmpl
  - /input/compose/powerwall/.env.tmpl
  - /input/compose/powerwall/pypowerwall.env.tmpl
  - /input/compose/powerwall/telegraf.conf.tmpl
  - /input/compose/powerwall/weather/weather411.conf.tmpl
  - /input/compose/qbittorrent/.env.tmpl
  - /input/compose/samba/.env.tmpl
  - /input/compose/samba/data/config.yml.tmpl
  - /input/compose/simple-monerod/.env.tmpl
  - /input/compose/ssh/.env.tmpl
  - /input/compose/syncthing/compose.yml.tmpl
  - /input/compose/syncthing/.env.tmpl
  - /input/compose/terraforming-mars/compose.yml.tmpl
  - /input/compose/terraforming-mars/.env.tmpl
  - /input/compose/tor-router/.env.tmpl
  - /input/compose/traefik/.env.tmpl
  - /input/compose/traefik/traefik.yml.tmpl
  - /input/compose/traefik/traefik_tls.yml.tmpl
  - /input/compose/usenet/.env.tmpl
  - /input/compose/vault/.env.tmpl
  - /input/compose/whoami/.env.tmpl
  - /input/compose/dovecot/.env.tmpl
  - /input/compose/mbsync/.env.tmpl
  - /input/compose/mumble-server/.env.tmpl
  - /input/compose/protonmail-bridge/.env.tmpl
  - /input/compose/weechat/.env.tmpl
  - /input/compose/weechat/run.sh.tmpl
  - /input/compose/grocy/.env.tmpl
  - /input/compose/changedetection/.env.tmpl

outputFiles:
  - /output/compose/vpn_general/.env
  - /output/compose/beets/.env
  - /output/compose/bitwarden/.env
  - /output/compose/busybox/.env
  - /output/compose/flexo/compose.yml
  - /output/compose/flexo/.env
  - /output/compose/imapfilter/.env
  - /output/compose/powerwall/.env
  - /output/compose/powerwall/pypowerwall.env
  - /output/compose/powerwall/telegraf.conf
  - /output/compose/powerwall/weather/weather411.conf
  - /output/compose/qbittorrent/.env
  - /output/compose/samba/.env
  - /output/compose/samba/data/config.yml
  - /output/compose/simple-monerod/.env
  - /output/compose/ssh/.env
  - /output/compose/syncthing/compose.yml
  - /output/compose/syncthing/.env
  - /output/compose/terraforming-mars/compose.yml
  - /output/compose/terraforming-mars/.env
  - /output/compose/tor-router/.env
  - /output/compose/traefik/.env
  - /output/compose/traefik/traefik.yml
  - /output/compose/traefik/traefik_tls.yml
  - /output/compose/usenet/.env
  - /output/compose/vault/.env
  - /output/compose/whoami/.env
  - /output/compose/dovecot/.env
  - /output/compose/mbsync/.env
  - /output/compose/mumble-server/.env
  - /output/compose/protonmail-bridge/.env
  - /output/compose/weechat/.env
  - /output/compose/weechat/run.sh
  - /output/compose/grocy/.env
  - /output/compose/changedetection/.env
