datasources:
  data:
    url: /data/container_data.json

context:
  container_data:
    url: /data/container_data.json

inputFiles:
  - /input/compose/.env.tmpl
  - /input/compose/flexo/flexo.env.tmpl
  - /input/compose/harbor/harbor.yml.tmpl
  - /input/compose/harbor/reset_password.sql.tmpl
  - /input/compose/powerwall/data/pypowerwall.env.tmpl
  - /input/compose/powerwall/data/telegraf.conf.tmpl
  - /input/compose/powerwall/data/weather411.conf.tmpl
  - /input/compose/smb/config.yml.tmpl
  - /input/compose/syncthing/compose.yml.tmpl
  - /input/compose/traefik/data/traefik.env.tmpl
  - /input/compose/traefik/data/traefik.yml.tmpl
  - /input/compose/vaultwarden/vault.env.tmpl
  - /input/quadlets/crowdin/.env.tmpl
  - /input/quadlets/syncthing/syncthing1.container.tmpl
  - /input/quadlets/syncthing/syncthing2.container.tmpl
  - /input/old/busybox/.env.tmpl
  - /input/old/mumble-server/mumble.env.tmpl
  - /input/old/wg_test/.env.tmpl

outputFiles:
  - /output/compose/.env
  - /output/compose/flexo/flexo.env
  - /output/compose/harbor/harbor.yml
  - /output/compose/harbor/reset_password.sql
  - /output/compose/powerwall/data/pypowerwall.env
  - /output/compose/powerwall/data/telegraf.conf
  - /output/compose/powerwall/data/weather411.conf
  - /output/compose/smb/config.yml
  - /output/compose/syncthing/compose.yml
  - /output/compose/traefik/data/traefik.env
  - /output/compose/traefik/data/traefik.yml
  - /output/compose/vaultwarden/vault.env
  - /output/quadlets/crowdin/.env
  - /output/quadlets/syncthing/syncthing1.container
  - /output/quadlets/syncthing/syncthing2.container
  - /output/old/busybox/.env
  - /output/old/mumble-server/mumble.env
  - /output/old/wg_test/.env
