name: mumble
services:
  mumble:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/mumblevoip/mumble-server:latest
    container_name: mumble
    user: 1104:1104
    env_file: mumble.env
    ports:
      - 64738:64738
    volumes:
      - /opt/appdata/mumble/data:/data:rw
      - /opt/appdata/mumble/certificates:/certificates:rw
    networks:
      frontend:
        ipv4_address: 172.34.0.2

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.34.0.0/16
        - subnet: fd34:1::/48
