services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    network_mode: container:vpn_general
    environment:
      - PUID=1003
      - PGID=1004
      - TZ=${TZ}
    volumes:
      - /mnt/container_data/grocy:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.tls=true"
      - "traefik.http.routers.grocy.tls.certresolver=stepca"
      - "traefik.http.routers.grocy.rule=Host(`grocy.$MY_DOMAIN`)"
      - "traefik.http.routers.grocy-websocket.rule=Host(`grocy.$MY_DOMAIN`) && Path(`/api/websocket`)"
      - "traefik.http.routers.grocy.entrypoints=websecure"
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
    restart: unless-stopped
