ARG fedora_version=35
#FROM registry.fedoraproject.org/fedora-toolbox:${fedora_version}
FROM localhost/base:${fedora_version}

ENV NAME=nvim-fedora-toolbox VERSION=${fedora_version}
LABEL com.github.containers.toolbox="true"                            \
      name="$NAME"                                                    \
      version="$VERSION"                                              \
      usage="This image is meant to be used with the toolbox command" \
      summary="Image includes Texlive, and various dependencies for editing markdown."

COPY extra-packages /
RUN dnf -y upgrade                        \
    && dnf -y install $(<extra-packages)  \
    && rm /extra-packages                 \
    && dnf clean all

RUN npm install -g neovim
RUN pip install pynvim
