services:
  vault-server:
    image: hashicorp/vault
    container_name: vault
    volumes:
      - /mnt/container_data/vault/config:/vault/config:rw
      - /mnt/container_data/vault/data:/vault/data:rw
    ports:
      - 127.0.0.1:8200:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    environment:
      - PUID=1003
      - PGID=1004
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault-server.tls=true"
      - "traefik.http.routers.vault-server.tls.certresolver=stepca"
      - "traefik.http.routers.vault-server.rule=Host(`vault.$MY_DOMAIN`)"
      - "traefik.http.routers.vault-server.entrypoints=websecure"

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
