name: vault
services:
  vault:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/hashicorp/vault
    container_name: vault
    cap_add:
      - IPC_LOCK
      - SETGID
      - SETUID
    user: 2005:2005
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - SKIP_SETCAP=1
      - SKIP_CHOWN=1
    ports:
      - 127.0.0.1:8200:8200
    volumes:
      - /opt/appdata/vault/config:/vault/config:rw
      - /opt/appdata/vault/data:/vault/data:rw
    networks:
      frontend:
        ipv4_address: 172.25.0.2
      traefik:

    entrypoint: vault server -config=/vault/config/vault.hcl

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: fd25:1::/48
  traefik:
    external: true
