services:
  wg3:
    image: ghcr.io/wfg/wireguard
    container_name: wg3
    hostname: wg3
    runtime: runc
    restart: unless-stopped
    cpus: 4
    mem_limit: 8g
    pids_limit: 2048
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    environment:
      - ALLOWED_SUBNETS=${NETWORK}/24
    volumes:
      - ${c_data}/wireguard/${WG}.conf:/etc/wireguard/wg0.conf
    ports:
      - 18080:18080
      - 18089:18089/tcp
      - 127.0.0.1:8558:8558
      - 127.0.0.1:8337:8337
    networks:
      frontend:
        ipv4_address: 172.22.0.2

networks:
  frontend:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
        - subnet: fd22:1::/48
