name: music
services:
  mpd:
    extends:
      file: ../_common/app.yml
      service: app-runc
    build:
      context: ../../build/mpd
      dockerfile: Dockerfile
      args:
        HOST_UID: 1003
        HOST_GID: 1003
    container_name: mpd
    hostname: mpd
    cpus: 1
    mem_limit: 1g
    pids_limit: 128
    environment:
      - MPD_OUTPUT_AUDIO_PIPE=1
      - TZ=${TIMEZONE:-Etc/UTC}
    ports:
      - 1704:1704/tcp
    volumes:
      - /opt/appdata/mpd/mpd.conf:/etc/mpd.conf:ro
      - /mnt/shared/music/library:/var/lib/mpd/music/library:ro
      - /opt/appdata/mpd:/var/lib/mpd/data
      - /opt/appdata/mpd/playlists:/var/lib/mpd/playlists
      - /opt/appdata/mpd/pipe:/audio
    networks:
      frontend:
        ipv4_address: 172.31.0.2
      traefik:

  snapcast:
    build:
      context: ../../build/snapserver
      dockerfile: Dockerfile
      args:
        HOST_UID: 1003
        HOST_GID: 1003
    container_name: snapcast
    restart: unless-stopped
    runtime: runc
    cap_drop:
      - ALL
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - /opt/appdata/snapcast/.config/snapserver/snapserver.conf:/etc/snapserver.conf:ro
      - /opt/appdata/snapcast:/var/lib/snapserver
      - /opt/appdata/mpd/pipe:/audio

    network_mode: service:mpd

  cyp:
    image: ghcr.io/ondras/cyp:master
    container_name: cyp
    restart: unless-stopped
    cap_drop:
      - ALL

    network_mode: service:mpd

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.31.0.0/16
        - subnet: fd31:1::/48
  traefik:
    external: true
