name: flexo
services:
  flexo:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/nroi/flexo
    container_name: flexo
    read_only: true
    user: 2001:2001
    env_file: flexo.env
    ports:
      - 9898:9898/tcp
    volumes:
      - /opt/appdata/flexo/latency_test_results.json:/var/cache/flexo/state/latency_test_results.json
      - /mnt/shared/flexo:/var/cache/flexo/pkg
    networks:
      frontend:
        ipv4_address: 172.26.0.2
      traefik:

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.26.0.0/16
        - subnet: fd26:1::/48
  traefik:
    external: true
