services:
  tor-router:
    container_name: tor-router
    image: tor-router
    build:
      context: ../build/tor-router/src/
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    restart: always
