name: navidrome
services:
  navidrome:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/deluan/navidrome:latest
    container_name: navidrome
    user: 1003:1004
    volumes:
      - /opt/appdata/navidrome:/data
      - /mnt/shared/music:/music:ro
    network_mode: container:wg3
