services:
  registry:
    image: docker.io/registry
    container_name: registry
    runtime: runsc-systrap
    restart: unless-stopped
    cpus: 2
    mem_limit: 8g
    pids_limit: 2048
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - /opt/appdata/registry:/var/lib/registry
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.${DOMAIN}]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    networks:
      frontend:
        ipv4_address: 172.30.0.2

  ui:
    image: docker.io/joxit/docker-registry-ui:latest
    container_name: ui
    runtime: runsc-systrap
    restart: unless-stopped
    cpus: 2
    mem_limit: 8g
    pids_limit: 2048
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    depends_on:
      - registry
    networks:
      frontend:
        ipv4_address: 172.30.0.3

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
        - subnet: fd30:1::/48
