name: beets
services:
  beets:
    image: lscr.io/linuxserver/beets
    container_name: beets
    network_mode: container:wg3
    runtime: runsc-systrap
    restart: unless-stopped
    cpus: 2
    mem_limit: 4g
    pids_limit: 1024
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - SETUID
      - SETGID
    environment:
      - PUID=1003
      - PGID=1003
    volumes:
      - /opt/appdata/beets:/config
      - /mnt/shared/music:/music
