services:
  beets:
    image: lscr.io/linuxserver/beets
    container_name: beets
    network_mode: container:vpn_general
    environment:
      - PUID=1003
      - PGID=1004
      - TZ=${TZ}
    volumes:
      - /mnt/container_data/beets:/config
      - /mnt/shared/music:/music
      - /mnt/shared/usenet/completed:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beets.tls=true"
      - "traefik.http.routers.beets.tls.certresolver=stepca"
      - "traefik.http.routers.beets.rule=Host(`beets.$MY_DOMAIN`)"
      - "traefik.http.routers.beets.entrypoints=websecure"
      - "traefik.http.services.beets.loadbalancer.server.port=8337"
    restart: unless-stopped
