name: beets
services:
  beets:
    extends:
      file: ../_common/app.yml
      service: linuxserver-app
    image: lscr.io/linuxserver/beets
    container_name: beets
    volumes:
      - /opt/appdata/beets:/config
      - /mnt/shared/music:/music
    network_mode: container:wg3
