services:
  imapfilter:
    build:
      context: .
      dockerfile: ../../build/imapfilter/Dockerfile
    container_name: imapfilter
    command: crond -f -l 8
    volumes:
      - /mnt/container_data/imapfilter/cron_tasks_folder/15min:/etc/periodic/15min/:ro
      - /mnt/container_data/imapfilter/cron_tasks_folder/hourly:/etc/periodic/hourly/:ro
      - /home/${USER1}/.imapfilter/primary.lua:/data/${USER1}_imapfilter:ro
      - /home/${USER2}/.imapfilter/imapfilter.conf:/data/${USER2}_imapfilter:ro
    restart: unless-stopped
