# TODO
# Notes
# gvisor sets the no_new_privs bit by default
# https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt
#
# Container also uses fixuid https://github.com/boxboat/fixuid which states:
# fixuid should only be used in development Docker containers. DO NOT INCLUDE
# in a production container image
services:
  monero:
    image: ghcr.io/sethforprivacy/simple-monerod:latest
    container_name: monerod
    network_mode: container:wg3
    runtime: runsc-kvm
    user: 1003:1003
    cpus: 2
    mem_limit: 4g
    pids_limit: 512
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - SETGID
      - SETUID
    volumes:
      - ${c_data}/monero/.bitmonero:/home/monero/.bitmonero
      - /mnt/shared/music:/music
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=18089"
      - "--no-igd"
      - "--no-zmq"
      - "--enable-dns-blocklist"
