name: stepca
services:
  stepca:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/smallstep/step-ca
    container_name: stepca
    read_only: true
    cap_add:
      - NET_BIND_SERVICE
    user: 2006:2006
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/stepca:/home/step:rw
