services:
  traefik:
    container_name: traefik
    hostname: traefik
    runtime: runsc-kvm
    restart: unless-stopped
    read_only: true
    mem_limit: 8g
    pids_limit: 2048
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: 1234:1234
    ports:
      - 80:8080
      - 443:4430
      - 443:4430/udp
    labels:
      - traefik.enable=true
      - traefik.docker.network=http_network
    volumes:
      - ${PWD}/traefik/data/traefik.yml:/etc/traefik/traefik.yml
      - ${PWD}/traefik/data/conf.d:/etc/traefik/conf.d
      - ${c_data}/traefik/acme.json:/etc/acme/acme.json
      - ${c_data}/traefik/certs:/etc/traefik/certs:ro
    env_file: ${PWD}/traefik/data/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - pypowerwall_backend
      - grafana_frontend
      - vault_frontend
      - syncthing1_frontend
      - syncthing2_frontend
      - flexo_frontend
      - wg1_qbt_frontend
      - wg2_usenet_frontend
      - wg3_general_frontend
