services:
  monerod:
    image: sethsimmons/simple-monerod:latest
    container_name: monerod
    volumes:
      - bitmonero:/home/monero
    ports:
      - 18080:18080
      - 18089:18089
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=18089"
      - "--no-igd"
      - "--no-zmq"
      - "--enable-dns-blocklist"
    restart: unless-stopped

  # autoheal:
  #     image: willfarrell/autoheal:latest
  #     container_name: autoheal
  #     restart: unless-stopped
  #     environment:
  #         AUTOHEAL_CONTAINER_LABEL: all
  #     volumes:
  #         - "/var/run/docker.sock:/var/run/docker.sock"

  watchtower:
      image: containrrr/watchtower:latest
      container_name: watchtower
      restart: unless-stopped
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  bitmonero:

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
