services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection.io
    volumes:
      - /mnt/container_data/changedetection:/datastore
    # - datastore-volume:/datastore
    ports:
      - 127.0.0.1:5000:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changedetection.tls=true"
      - "traefik.http.routers.changedetection.tls.certresolver=stepca"
      - "traefik.http.routers.changedetection.rule=Host(`changedetection.$MY_DOMAIN`)"
      - "traefik.http.routers.changedetection.entrypoints=websecure"
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"
    restart: always

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}

# volumes:
#  changedetection-data:
