name: vaultwarden
services:
  vaultwarden:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/vaultwarden/server:latest
    container_name: bitwarden
    read_only: true
    cap_add:
      - CHOWN
    user: 1003:1003
    environment:
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - ROCKET_PORT=8558
    env_file: vault.env
    volumes:
      - /opt/appdata/vaultwarden:/data
    network_mode: container:wg3
