name: wg3_general
services:
  wg3:
    extends:
      file: ../_common/app.yml
      service: wireguard-app
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wg3
    hostname: wg3
    ports:
      - 127.0.0.1:8558:8558
      - 127.0.0.1:8337:8337
      - 127.0.0.1:4533:4533
      - 127.0.0.1:8083:80
      - 127.0.0.1:8080:8080
    volumes:
      - /opt/appdata/wireguard/${WG3}.conf:/config/wg_confs/wg0.conf
    networks:
      frontend:
        ipv4_address: 172.23.0.2
      traefik:
        ipv4_address: 172.20.0.4

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.23.0.0/16
        - subnet: fd23:1::/48
  traefik:
    external: true
