services:
  vault:
    image: docker.io/hashicorp/vault server
    container_name: vault
    runtime: runsc-kvm
    restart: unless-stopped
    user: 1104:1104
    cpus: 2
    mem_limit: 8g
    pids_limit: 2048
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - IPC_LOCK
      - SETGID
      - SETUID
    environment:
      VAULT_ADDR=http://0.0.0.0:8200
      VAULT_API_ADDR=http://0.0.0.0:8200
      SKIP_SETCAP=1
      SKIP_CHOWN=1
    volumes:
      - ${c_data}/vault/config:/vault/config:rw
      - ${c_data}/vault/data:/vault/data:rw
    ports:
      - 127.0.0.1:8200:8200
    networks:
      vault-frontend:
        ipv4_address: 172.23.0.2

networks:
  vault-frontend:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
        - subnet: fd23:1::/48
