name: cinny
services:
  cinny:
    image: ghcr.io/cinnyapp/cinny:latest
    container_name: cinny
    network_mode: container:wg3
    runtime: runsc-systrap
    restart: unless-stopped
    # user: 1003:1003
    cpus: 2
    mem_limit: 4g
    pids_limit: 512
    # read_only: true
    security_opt:
      - no-new-privileges:true
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    volumes:
      - /opt/appdata/cinny/config.json:/app/config.json
