name: cinny
services:
  cinny:
    extends:
      file: ../_common/app.yml
      service: app
    image: ghcr.io/cinnyapp/cinny:latest
    container_name: cinny
    # user: 1003:1003
    # read_only: true
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /opt/appdata/cinny/config.json:/app/config.json
    network_mode: container:wg3
