name: samba
services:
  samba:
    extends:
      file: ../_common/app.yml
      service: app-runc
    image: docker.io/crazymax/samba
    container_name: samba
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - NET_RAW
      - SETUID
      - SETGID
    environment:
      - SAMBA_LOG_LEVEL=0
    volumes:
      - ./config.yml:/data/config.yml
      - /home/${U1}:/samba/${U1}
      - /home/${U2}:/samba/${U2}
      - /mnt/shared:/samba/shared
    network_mode: host
