name: samba
services:
  samba:
    image: docker.io/crazymax/samba
    container_name: samba
    network_mode: host
    runtime: runc
    restart: unless-stopped
    cpus: 2
    mem_limit: 1g
    pids_limit: 512
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - NET_RAW
      - SETUID
      - SETGID
    volumes:
      - ./config.yml:/data/config.yml
      - /home/${U1}:/samba/${U1}
      - /home/${U2}:/samba/${U2}
      - /mnt/shared:/samba/shared
    environment:
      - SAMBA_LOG_LEVEL=0
