name: caddy
services:
  caddy:
    extends:
      file: ../_common/app.yml
      service: app-runc
    image: docker.io/caddy
    container_name: caddy
    pids_limit: 512
    read_only: true
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/appdata/caddy/conf:/etc/caddy
      - /opt/appdata/caddy/site:/srv
      - /opt/appdata/caddy/data:/data
      - /opt/appdata/caddy/config:/config
    networks:
      frontend:
        ipv4_address: 172.33.0.2

networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.33.0.0/16
        - subnet: fd33:1::/48
