services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - "${PYPOWERWALL_PORTS:-8675:8675}"
    environment:
      LEGO_CA_CERTIFICATES: "/etc/traefik/certs/root.crt"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      # - "./traefik_tls.yml:/etc/traefik/traefik_tls.yml:ro"
      - "/mnt/container_data/traefik/certs:/etc/traefik/certs:ro"
      - "acme:/etc/acme"
volumes:
  acme:

networks:
  traefik-proxy:
    external: true
