name: traefik
services:
  traefik:
    extends:
      file: ../_common/app.yml
      service: app
    build:
      context: ../../build/traefik
      dockerfile: Dockerfile
    container_name: traefik
    image: localhost/traefik
    # image: docker.io/traefik
    hostname: traefik
    read_only: true
    user: 1003:1003
    environment:
      - LEGO_CA_CERTIFICATES=/etc/traefik/certs/root.crt
      - domain=${DOMAIN}
    env_file: ./data/traefik.env
    ports:
      - 8675:8675
      - 80:8080
      - 443:4430
      - 443:4430/udp
    volumes:
      - ./data/traefik.yml:/etc/traefik/traefik.yml
      - ./data/conf.d:/etc/traefik/conf.d:ro
      - /opt/appdata/traefik/acme.json:/etc/acme/acme.json:rw
      - /opt/appdata/traefik/certs:/etc/traefik/certs:ro
    networks:
      - traefik
networks:
  traefik:
    external: true
