ARG fedora_version=39
FROM registry.fedoraproject.org/fedora-toolbox:${fedora_version}

ENV NAME=base-fedora-toolbox VERSION=${fedora_version}
LABEL com.github.containers.toolbox="true"                                  \
      name="$NAME"                                                          \
      version="$VERSION"                                                    \
      usage="This image is meant to be used with the toolbox command"       \
      summary="Base system toolbox image. Use to install system wide tools"

COPY extra-packages /
RUN dnf -y upgrade                                                                                                    \
    && dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm             \
    && dnf -y install $(<extra-packages)                                                                              \
    && rm /extra-packages                                                                                             \
    && dnf clean all
