name: rss
services:
  miniflux-db:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/library/postgres:18-trixie
    container_name: miniflux-db
    user: "999:999"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - miniflux.env
    volumes:
      - /opt/appdata/miniflux:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U miniflux -d miniflux"]
      interval: 3s
      timeout: 3s
      retries: 5

    network_mode: container:wg3

  miniflux:
    extends:
      file: ../_common/app.yml
      service: app
    image: docker.io/miniflux/miniflux:latest
    container_name: miniflux
    environment:
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - BASE_URL=https://rss.${DOMAIN}
    env_file:
      - miniflux.env
    depends_on:
      miniflux-db:
        condition: service_healthy
    network_mode: container:wg3
